# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_config/configuration.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1fgrpc_config/configuration.proto\"\x1b\n\x07\x61\x64\x64ress\x12\x10\n\x08zip_code\x18\x01 \x01(\t\"S\n\x0b\x61\x64\x64ressData\x12\x10\n\x08zip_code\x18\x01 \x01(\t\x12\x0e\n\x06street\x18\x02 \x01(\t\x12\x14\n\x0cneighborhood\x18\x03 \x01(\t\x12\x0c\n\x04\x63ity\x18\x04 \x01(\t26\n\x0eGetAddressData\x12$\n\x08get_data\x12\x08.address\x1a\x0c.addressData\"\x00\x62\x06proto3')

_ADDRESS = DESCRIPTOR.message_types_by_name['address']
_ADDRESSDATA = DESCRIPTOR.message_types_by_name['addressData']
address = _reflection.GeneratedProtocolMessageType('address', (_message.Message,), {
    'DESCRIPTOR': _ADDRESS,
    '__module__': 'grpc_config.configuration_pb2'
    # @@protoc_insertion_point(class_scope:address)
})
_sym_db.RegisterMessage(address)

addressData = _reflection.GeneratedProtocolMessageType('addressData', (_message.Message,), {
    'DESCRIPTOR': _ADDRESSDATA,
    '__module__': 'grpc_config.configuration_pb2'
    # @@protoc_insertion_point(class_scope:addressData)
})
_sym_db.RegisterMessage(addressData)

_GETADDRESSDATA = DESCRIPTOR.services_by_name['GetAddressData']
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _ADDRESS._serialized_start = 35
    _ADDRESS._serialized_end = 62
    _ADDRESSDATA._serialized_start = 64
    _ADDRESSDATA._serialized_end = 147
    _GETADDRESSDATA._serialized_start = 149
    _GETADDRESSDATA._serialized_end = 203
# @@protoc_insertion_point(module_scope)
