# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc_config import configuration_pb2 as grpc__config_dot_configuration__pb2


class GetAddressDataStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_data = channel.unary_unary(
            '/GetAddressData/get_data',
            request_serializer=grpc__config_dot_configuration__pb2.address.SerializeToString,
            response_deserializer=grpc__config_dot_configuration__pb2.addressData.FromString,
        )


class GetAddressDataServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_data(self, request, context):
        """Method definition
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GetAddressDataServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'get_data': grpc.unary_unary_rpc_method_handler(
            servicer.get_data,
            request_deserializer=grpc__config_dot_configuration__pb2.address.FromString,
            response_serializer=grpc__config_dot_configuration__pb2.addressData.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'GetAddressData', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class GetAddressData(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_data(request,
                 target,
                 options=(),
                 channel_credentials=None,
                 call_credentials=None,
                 insecure=False,
                 compression=None,
                 wait_for_ready=None,
                 timeout=None,
                 metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GetAddressData/get_data',
                                             grpc__config_dot_configuration__pb2.address.SerializeToString,
                                             grpc__config_dot_configuration__pb2.addressData.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
